todoonrails/config/routes.rb
Rails.application.routes.draw do
  get 'todolists/index'

  resources :todolists

  root 'todolists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todoonrails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

todoonrails/app/models/todolist.rb
class Todolist < ApplicationRecord
    validates :description , presence: true, length: {minimum:5}
end

todoonrails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

todoonrails/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
    def index
        @todos = Todolist.all
    end
    
    def show
        
        return not_found unless Todolist.exists?(id: params[:id])
        
        @todo = Todolist.find(params[:id])
    end

    def new
        @todo = Todolist.new
    end

    def edit
        
        return not_found unless Todolist.exists?(id: params[:id])

        @todo = Todolist.find(params[:id])
    end
     
    def create
        @todo = Todolist.new(todo_params)
       
        if @todo.save
            redirect_to @todo
        else
            render 'new'
        end

      end
    
    def update
        
        return not_found unless Todolist.exists?(id: params[:id])

        @todo = Todolist.find(params[:id])
        
        if @todo.update(todo_params)
            redirect_to @todo
        else
            render 'edit'
        end
    end

    def destroy
        
        return not_found unless Todolist.exists?(id: params[:id])

        @todo = Todolist.find(params[:id])
        
        @todo.destroy
       
        redirect_to todolists_path
      end
        
    private
        def todo_params
            params.require(:todo).permit(:description, :priority, :duedate)
        end
    
    def not_found
        raise ActionController::RoutingError.new('Not Found')
        end
end

todoonrails/app/helpers/application_helper.rb
module ApplicationHelper
end

todoonrails/app/helpers/todolists_helper.rb
module TodolistsHelper
end

todoonrails/app/helpers/todos_helper.rb
module TodosHelper
end

todoonrails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoonrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

todoonrails/app/views/todolists/_form.html.erb
<%= form_with(model: @todo, local: true, scope: :todo) do |form| %>

<% if @todo.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@todo.errors.count, "error") %> prohibited
        this todo from being saved:
    </h2>
    <ul>
        <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<p>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
</p>

<p>
    <%= form.label :Priority %><br>

    <%= form.select :priority, [["High", "High"], ["Moderate", "Moderate"], ["Low", "Low"]] %>
</p>

<p>
    <%= form.label :Priority %><br>

    <%= form.datetime_field :duedate %>
</p>

<p>
    <%= form.submit %>
</p>
<% end %>

todoonrails/app/views/todolists/edit.html.erb
<h1> Edit Task </h1>

<%= render 'form' %>

<%= link_to 'Back to all Tasks', todolists_path %>

todoonrails/app/views/todolists/index.html.erb
<h1>To-do List</h1>

<%= link_to 'New Task', new_todolist_path %>

<table border=1>
    <tr>
        <th>Id</th>
        <th>Description</th>
        <th>Priority</th>
        <th>Due Date</th>
        <th>View</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

    <% @todos.each do |todo| %>
    <tr>
        <td><%= todo.id %></td>
        <td><%= todo.description %></td>
        <td><%= todo.priority %></td>
        <td>
            <% if (todo.duedate) %>
            <%= todo.duedate %>
            <% else %>
            Na
            <% end %>
        </td>
        <td><%= link_to 'Show', todolist_path(todo) %></td>
        <td><%= link_to 'Edit', edit_todolist_path(todo) %></td>
        <td><%= link_to 'Delete', todolist_path(todo),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>

todoonrails/app/views/todolists/new.html.erb
<h1> Create new Task </h1>

<%= render 'form' %>


<%= link_to 'Back to all Tasks', todolists_path %>

todoonrails/app/views/todolists/show.html.erb
<p>
    <strong>id:</strong>
    <%= @todo.id %>
</p>

<p>
    <strong>Description:</strong>
    <%= @todo.description %>
</p>

<p>
    <strong>Priority:</strong>
    <%= @todo.priority %>
</p>

<p>
    <strong>Duedata:</strong>
    <% if (@todo.duedate) %>
    <%= @todo.duedate %>
    <% else %>
    Na
    <% end %>
</p>


<%= link_to 'Back to all Tasks', todolists_path %>